### ISSUE TITLE
Candle build is broken again

### ISSUE THREAD

**Issue by junghans** [junghans/proxy-ci#20]
https://travis-ci.org/proxyapps/proxy-ci/builds/436623735

**Comment by rspavel** [comment]
Should be fixed by https://github.com/spack/spack/pull/9425

I have a modified .travis.yml that does the same locally, but let's see how long it takes to upstream this. Regardless, we should probably contact the candle devs and try to figure out which of our manual specs are required and which are due to environment issues

**Comment by junghans** [comment]
it happened again: https://travis-ci.org/proxyapps/proxy-ci/builds/457242442

**Comment by junghans** [comment]
Ping @rspavel
